site_name: mlignore
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
  features:
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true

nav:
  - Home: index.md
  - Usage: usage.md
  - API Reference: reference.md
